# Generated by Django 5.0.2 on 2024-02-29 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Clothes', 'Clothes'), ('Books', 'Books'), ('Shoes', 'Shoes'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='donations/')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
