# Generated by Django 5.0.1 on 2024-03-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doant', '0002_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
