# Generated by Django 5.0.1 on 2024-03-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doant', '0006_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doant.userdetail'),
            preserve_default=False,
        ),
    ]
